name: Release
on:
  create:
    tags:
    - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Validate GoReleaser config
      uses: goreleaser/goreleaser-action@v5
      with:
        args: check
        workdir: .
      env:
        GORELEASER_VERSION: latest

    - name: Build Linux packages
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --clean
        workdir: .
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GOOS: linux
        GOARCH: amd64
        GORELEASER_VERSION: latest